# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Flick_MovieViewer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flick_MovieViewer
  pod 'AFNetworking', '~> 2.6'
  pod 'MBProgressHUD'
end
